# This is a basic workflow to help you get started with Actions
name: Packj NPM Registry Firewall Demo

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "packj-audit"
  packj-npm-registry-firewall:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Setup Packj NPM registry firewall
        uses: ossillate-inc/packj-npm-registry-firewall-action@main
        with:
          PACKJ_FIREWALL_TOKEN: ${{ secrets.PACKJ_FIREWALL_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install
        shell: bash
